from typing import Any, Optional

from pydantic import BaseModel, ConfigDict


class ExtractedCase(BaseModel):
    """Structured case signals extracted by the LLM (ports src/lib/types.ts)."""

    model_config = ConfigDict(extra="ignore")

    caseName: Optional[str] = None
    defendant: Optional[str] = None
    victim: Optional[str] = None
    crimeType: Optional[str] = None
    jurisdiction: Optional[str] = None
    state: Optional[str] = None
    approximateYear: Optional[str] = None
    keywords: list[str] = []
    confidence: str = "low"  # "high" | "medium" | "low"


class ScoredCandidate(BaseModel):
    """A scored search result from CourtListener or Wikipedia."""

    model_config = ConfigDict(extra="ignore")

    title: str
    source: str  # "courtlistener" | "wikipedia"
    score: float
    url: Optional[str] = None
    snippet: Optional[str] = None
    metadata: Optional[dict[str, str]] = None


class CaseOverview(BaseModel):
    """Structured case overview generated by the LLM."""

    model_config = ConfigDict(extra="ignore")

    summary: str = ""
    timeline: list[str] = []
    people: list[dict[str, str]] = []  # [{name, role}]
    legalOutcome: str = ""
    faq: list[dict[str, str]] = []  # [{question, answer}]


class CaseAnalysis(BaseModel):
    """The full analysis response returned by POST /analyze."""

    model_config = ConfigDict(extra="ignore")

    extracted: ExtractedCase
    originalExtracted: ExtractedCase
    candidates: list[ScoredCandidate] = []
    wikiSummary: Optional[str] = None
    wikiUrl: Optional[str] = None
    wikiThumbnail: Optional[str] = None
    refinementNames: list[str] = []
    sourceType: str  # "youtube" | "article"
    sourceTitle: Optional[str] = None
    overview: CaseOverview = CaseOverview()


class ExtractedContent(BaseModel):
    """Normalized source content (ports src/lib/types.ts ExtractedContent)."""

    model_config = ConfigDict(extra="ignore")

    sourceType: str  # "youtube" | "article"
    title: Optional[str] = None
    text: str
    url: str


# ---------------------------------------------------------------------------
# Cache-specific types (matching the JSON stored in Upstash Redis)
# ---------------------------------------------------------------------------


class CachedCourtListenerResult(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: str = ""
    cluster_id: str = ""
    caseName: str = ""
    court: str = ""
    dateFiled: str = ""
    absolute_url: str = ""
    snippet: str = ""
    score: float = 0.0


class CachedWikiResult(BaseModel):
    model_config = ConfigDict(extra="ignore")

    candidates: list[ScoredCandidate] = []
    summary: Optional[str] = None
    url: Optional[str] = None
    thumbnail: Optional[str] = None