import type { Metadata } from "next";
import "./globals.css";
import { Inter, Merriweather, Archivo, Space_Mono } from 'next/font/google'

import Home from "./components/Home";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-merriweather",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-archivo",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full ${inter.variable} ${merriweather.variable} ${spaceMono.variable} ${archivo.variable}`}>
      <body className="h-full flex flex-col">
        <Home>{children}</Home>
      </body>
    </html>
  );
}
